## Exercise 1: 
Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5 matrix.

In [1]:
import numpy as np
import pandas as pd

In [2]:
# creating numpy array
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
# reshaping to 2x5 matrix

reshaped_arr = arr.reshape(2,5)
print('2x5 matrix:\n',reshaped_arr)

2x5 matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## Exercise 2:
Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index.

In [9]:
# creating numpy array

arr = np.arange(1,21)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [11]:
# extract the element b/w 5th & 15th index

extracted_elements= arr[5:16]
print(extracted_elements)

[ 6  7  8  9 10 11 12 13 14 15 16]


## Exercise 3:
Create a Pandas series with the following data: {'apples': 3, 'bananas': 2, 'oranges': 1}. Then, add a new item to the series with the key 'pears' and the value 4.

In [13]:
# create a pandas series

series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})
series

apples     3
bananas    2
oranges    1
dtype: int64

In [15]:
# adding new item to the series

series['pears'] = 4
series

apples     3
bananas    2
oranges    1
pears      4
dtype: int64

## Exercise 4:
Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data. 

In [19]:
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Emma', 'Frank', 'Grace', 'Hannah', 'Ian', 'Jack'],
    'age': [20,22,24,26,28,30,32,35,36,40],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'M']
}
df = pd.DataFrame(data)
df

name  age gender
0    Alice   20      F
1      Bob   22      M
2  Charlie   24      M
3    David   26      M
4     Emma   28      F
5    Frank   30      M
6    Grace   32      F
7   Hannah   35      F
8      Ian   36      M
9     Jack   40      M

## Exercise 5:
Add a new column to the data frame created in question 1, called occupation. The values for this column should be Programmer, Manager, and Analyst, corresponding to the rows in the dataframe.

In [21]:
# adding the new column 'occupation'

occupation = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager','Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']

df['Occupation'] = occupation
df

name  age gender  Occupation
0    Alice   20      F  Programmer
1      Bob   22      M     Manager
2  Charlie   24      M     Analyst
3    David   26      M  Programmer
4     Emma   28      F     Manager
5    Frank   30      M     Analyst
6    Grace   32      F  Programmer
7   Hannah   35      F     Manager
8      Ian   36      M     Analyst
9     Jack   40      M  Programmer

## Exercise 6:
Select the rows of the dataframe where the age is greater than or equal to 30. 

In [25]:
df[df['age'] >= 30]

name  age gender  Occupation
5   Frank   30      M     Analyst
6   Grace   32      F  Programmer
7  Hannah   35      F     Manager
8     Ian   36      M     Analyst
9    Jack   40      M  Programmer

## Exercise 7: 
Convert this dataframe to a csv file and read that csv file, finally display the contents.



In [27]:
# converting dataframe to csv file

df.to_csv('data.csv', index = False)

In [29]:
# read the csv file

csv_file = pd.read_csv('data.csv')
csv_file

name  age gender  Occupation
0    Alice   20      F  Programmer
1      Bob   22      M     Manager
2  Charlie   24      M     Analyst
3    David   26      M  Programmer
4     Emma   28      F     Manager
5    Frank   30      M     Analyst
6    Grace   32      F  Programmer
7   Hannah   35      F     Manager
8      Ian   36      M     Analyst
9     Jack   40      M  Programmer